# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telphone',
            field=models.CharField(max_length=10, verbose_name='telefone'),
        ),
    ]
