# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_jornada', '0001_initial'),
        ('app_perfil', '0001_initial'),
        ('app_usuario', '0002_auto_20171205_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jornada',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app_jornada.Jornada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app_perfil.Perfil'),
            preserve_default=False,
        ),
    ]
