# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0003_auto_20171205_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jornada',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('Administrador do Sistema', b'Administrador do Sistema'), ('Lider da Equipe', b'Lider da Equipe'), ('Promotor de Vendas', b'Promotor de Vendas')], max_length=150),
        ),
    ]
